---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: 192.168.33.10 }]
  vagrantfiles:
    - Vagrant_fixed_disks.rb
  customize:
    cpus: 6
    memory: 24576
    storagectl:
      - name: "SATA Controller"
        hostiocache: "off"
  synced_folders:
    - ["/Users/jpbadger/Library/Caches/vagrant/%{instance_name}", "/srv/data", "create: true, type: :rsync"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[maps_server::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
